camel:
  springboot:
    main-run-controller: true
spring:
  profiles:
    active: default
  application:
    name: Integration-Brunel-SAP_CEVA-PURORD

ftp:
  ceva:
    server: ukftp-auto.oup.com
    pickuplocation: 
      plant1: to_OUP/plant_7410/RECADV
      plant2: to_OUP/plant_7430/RECADV
    port: 22
    username: brunel_test_OUP
    password: RAW(!D9ElUcMktDLIqd&J^6Ye)
    fileFilter: cevaextract_*.xml
    ftpOptions: username=${ftp.ceva.username}&password=${ftp.ceva.password}&antInclude=${ftp.ceva.fileFilter}&useUserKnownHostsFile=false&delete=true&sortBy=file:modified
    sftpPathPlant1: file:plant_7410
    sftpPathPlant2: file:plant_7430
    # sftpPathPlant1: sftp:{{ftp.ceva.server}}:{{ftp.ceva.port}}/{{ftp.ceva.pickuplocation.plant1}}?{{ftp.ceva.ftpOptions}}
    # sftpPathPlant2: sftp:{{ftp.ceva.server}}:{{ftp.ceva.port}}/{{ftp.ceva.pickuplocation.plant2}}?{{ftp.ceva.ftpOptions}}

sap:
  connection:
    gwhost: indsapdev.in.oup.com
    gwserv: sapgw00
    progid: INQ_BRUNEL_INBOUND
    client: 21
    user: CHINTHAR
    passwd: Sainath-3
    lang: EN
    group: 
    mshost: 10.45.6.7
    msserv: 3600
    r3name: IND
    connectionCount: 2
    recipientPort: SAPIND
    recipientPartnerNumber: CEVA_INDEL
    senderPort: BRUNEL_INBOUND
    senderPartnerNumber: DISPATCHER
    idocType: DELVRY03
    messageType: WHSCON
    endpoint: sap-idoc-destination:sapInbound:DELVRY03
    # endpoint: file:outbox

file:
  location: backup
  # location: /OUT/${spring.application.name}
  XML: 
    name: CEVA-RECADV-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/01-FromCEVA/$simple{date:now:yyyy/MM/dd}
  IDOC: 
    name: SAP-WHSCON-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/02-ToSAP/$simple{date:now:yyyy/MM/dd}

---

spring:
  profiles: dev

ftp:
  ceva:
    server: ukftp-auto.oup.com
    pickuplocation: 
      plant1: to_OUP/plant_7410/RECADV
      plant2: to_OUP/plant_7430/RECADV
    port: 22
    username: brunel_test_OUP
    password: RAW(!D9ElUcMktDLIqd&J^6Ye)
    fileFilter: cevaextract_*.xml
    ftpOptions: username=${ftp.ceva.username}&password=${ftp.ceva.password}&antInclude=${ftp.ceva.fileFilter}&useUserKnownHostsFile=false&delete=true&sortBy=file:modified
    sftpPathPlant1: file:plant_7410
    sftpPathPlant2: file:plant_7430
    # sftpPathPlant1: sftp:{{ftp.ceva.server}}:{{ftp.ceva.port}}/{{ftp.ceva.pickuplocation.plant1}}?{{ftp.ceva.ftpOptions}}
    # sftpPathPlant2: sftp:{{ftp.ceva.server}}:{{ftp.ceva.port}}/{{ftp.ceva.pickuplocation.plant2}}?{{ftp.ceva.ftpOptions}}

sap:
  connection:
    gwhost: qukeccdb01.uk.oup.com
    gwserv: sapgw00
    progid: R3Q_CEVA_INBOUND
    client: 10
    user: CEVAUKIDOC
    passwd: Cevaint@11
    lang: EN
    group: R3QSAP
    mshost: qukeccsc01.uk.oup.com
    msserv: 3600
    r3name: R3Q
    connectionCount: 2
    recipientPort: SAPR3Q
    recipientPartnerNumber: CEVA_INDEL
    senderPort: CEVA_INB
    senderPartnerNumber: DISPATCHER
    idocType: DELVRY03
    messageType: WHSCON
    endpoint: sap-idoc-destination:sapukDestination:DELVRY03

file:
  location: /OUT/${spring.application.name}
  XML: 
    name: CEVA-RECADV-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/01-FromCEVA/$simple{date:now:yyyy/MM/dd}
  IDOC: 
    name: SAP-WHSCON-$simple{header.InterChangeID}_$simple{header.OrderID}.xml
    backup: file:${file.location}/02-ToSAP/$simple{date:now:yyyy/MM/dd}